name: Botni Uyg'oq Saqlash

on:
  schedule:
    # Har 15 daqiqada bir marta ishga tushadi
    - cron: '*/15 * * * *'
  workflow_dispatch: # Qo'lda ishga tushirish imkoniyati

jobs:
  ping_site:
    runs-on: ubuntu-latest
    steps:
      - name: Saytga signal yuborish
        run: curl -I https://audiov.streamlit.app
        
